name: 'E2E Test Report'

on:
  workflow_run:
    workflows: ['CI']                     # runs after CI workflow
    types:
      - completed

permissions:
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2.1.1
        with:
          artifact: /e2e-test-reports-(.*)/
          name: JEST Tests $1               # Name of the check run which will be created
          path: 'report*.xml'               # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results
          fail-on-empty: 'true'
