name: Adds all issues

on:
  issues:
    types:
      - opened

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write
      issues: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
        with:
          project-url: https://github.com/orgs/kubernetes/projects/104
          github-token: ${{ secrets.PROJECT_WRITER }}
